### ISSUE TITLE
Possible to set specific sizes for different breakpoints? Also round to whole numbers?

### ISSUE THREAD

**Issue by dlewand691** [project-rfs/rfs#11]
Wondering if it's possible to set up a set of breakpoints and set a specific size to scale down to? 

For example:
```
> 1024, H1 = 96
< 1024 but > 768, H1 = 76px
> 768 but > 480, H1 = 48px
< 480, H1 = 36px
```

Also, can the rounding be controlled to be whole numbers, or at least to 1 or 2 decimals?

thank you!

**Comment by MartijnCuppens** [comment]
RFS is made to automatically rescale the font size, while keeping a relation between all the font sizes being used, without the need to define the font-size for multiple screen widths. 

Maybe this technique might be interesting if you want to have control over your font-sizes at certain screen widths: https://www.smashingmagazine.com/2015/06/responsive-typography-with-sass-maps/

About the rounding, this is a setting that can be changed in sass, see https://stackoverflow.com/questions/10369643/rounding-numbers-in-sass-and-adjusting-the-amount-of-decimals

**Comment by dlewand691** [comment]
Right, the auto rescaling is exactly why I love RFS over other solutions that just "snap" to the next font size. The rescaling helps with long headlines at smaller resolutions (among other things) which is why I think RFS is a solid solution and have enjoyed using it.

Thanks for the links, I'll tinker with the rounding and share anything that might be useful.
