### ISSUE TITLE
Add setting to make font-size grow even after breakpoint ?

### ISSUE THREAD

**Issue by Satche** [project-rfs/rfs#12]
The title seems silly, but let me explain:

Let say I want a 50px font-size at 1200px breakpoint. Actual behaviour will set this at the maximum font-size. Would it be legit to have an extra breakpoint setting as a "helper" ? The font-size is at 50px when it reach 1200px viewport, but continue to scale as the viewport do.

**Comment by MartijnCuppens** [comment]
This is quite a "dangerous" thing to do. If you don't limit the font-size at a certain point, some text will be superhuge at bigger screens (like 2560px monitors). Also, the base font-size will not scale up, so the relationship between small and large font sizes will be off balance. 

Maybe it's just better to increase your `$rfs-breakpoint`?

**Comment by Satche** [comment]
Well I thought about it.. but if I increase `$rfs-breakpoint` to, let say, 2400px; my font-size will be at 50px at 2400px, but much lower at 1200px.

What if I want a breakpoint-max at 1800px to avoid super-huge font-size; but, due to the spec, want my specific font-size at the 1200 breakpoint ? I don't know if it's a too specific case.

**Comment by MartijnCuppens** [comment]
Hmm, I think this case indeed is a bit specific but I'll leave this issue open for a while, just in case there are more people who want something like this.
