### ISSUE TITLE
Safari iframe resize bug

### ISSUE THREAD

**Issue by MartijnCuppens** [project-rfs/rfs#14]
Right now, the font sizes do not rescale in iframes in safari when the iframe is rescaled. It's possible to avoid this by adding `min-width: 0vw;` in the media queries of RFS.
This is not the most ideal solution, and should be disabled by default.

Demo: https://codepen.io/MartijnCuppens/pen/djYBGW

- [x] Fix bug in scss
- [x] Fix bug in sass
- [x] Fix bug in PostCSS
- [x] Fix bug in Stylus
- [x] Fix bug in less
- [x] Update readme

In this demo another codepen is secretly loaded which adds some dirty code to fix this: https://codepen.io/MartijnCuppens/pen/ZBjdMy?editors=1100

**Comment by MartijnCuppens** [comment]
Fixed in v7.1.3

**Comment by mblackritter** [comment]
I wonder if this might be set as a default for the demos, because it could be rather surprising to initially see it in a non working state. 😍🥰

At least It buzzled me, beside that I knew it generally works, because I already implemented it.
