### ISSUE TITLE
Stylus unitless bug

### ISSUE THREAD

**Issue by NZX-DeSiGN** [project-rfs/rfs#22]
Hi,

I just discovered your mixin, it seems to be awesome !
Correct me if I'm wrong, but I found a bug in the stylus version : ``rfs(64)``  produce ``font-size: 64`` in CSS.

I think the problem is **line 60** of the stylus version, you forgot the unitless test like in the SASS version. 

**Replacing**
``(unit($fs) != "px" and unit($fs) != "rem")``
**by this seems to do the job** 
``(unit($fs) != "" and unit($fs) != "px" and unit($fs) != "rem") ``

P.S : I also think would be better to put unit($fs) in a variable to avoid repeating it in the if block

**Comment by MartijnCuppens** [comment]
Thanks @NZX-DeSiGN! I'll have a look at this this weekend.

Or if you wish, you can always open a PR with your suggestions 😉

**Comment by MartijnCuppens** [comment]
Fix is available in v7.1.5
