### ISSUE TITLE
PostCSS Example

### ISSUE THREAD

**Issue by DanielSokil** [project-rfs/rfs#27]
I have tried this project with PostCSS and cannot get it to work, could you please provide an example of how to use correctly?

**Comment by MartijnCuppens** [comment]
There are node and gulp examples available in `examples/postcss`:
https://github.com/project-rfs/rfs/tree/master/examples/postcss

Does this help you?

**Comment by DanielSokil** [comment]
This is how I'm currently using PostCSS in a project:
```javascript
const plugins = [
	require('postcss-import'),
	require('postcss-cssnext')
];
return postcss(plugins)
	.process(content, {
		from: 'src',
		map: { inline: false }
	})
	.then((result) => ({
		code: result.css.toString(),
		map: result.map.toString()
	}));
```
I can include `rfs` inside the `postcss.process` function?

**Comment by MartijnCuppens** [comment]
It's a bit hard to debug your whole webpack setup and I must admit I'm not that experienced with webpack. The way you use `RFS` looks ok if I compare it the the simple node example: https://github.com/project-rfs/rfs/blob/master/examples/postcss/node/index.js, there is probably something wrong with the setup in general.

If you find out what's wrong or if you have any suggestion to improve the documentation, let me know

**Comment by MartijnCuppens** [comment]
This example I mentioned should be enough to help you out. Closing this.
